[tool.poetry]
name = "scengen"
version = "0.1.0"
description = ""
authors = ["Jonas Soenen <jonas.soenen@kuleuven.be>"]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
